#!/bin/bash

# AppRun script for LiteClip AppImage

# Get the directory where this AppImage/AppRun is located
APPDIR="$(dirname "$(readlink -f "${0}")")"

# Export necessary environment variables
export PATH="${APPDIR}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"
export DOTNET_ROOT="${APPDIR}/usr/bin/liteclip"

# Change to the LiteClip directory to ensure relative file loading works
cd "${APPDIR}/usr/bin/liteclip"

# Execute the application
exec ./liteclip "$@"
